version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/WordPress
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/change_permissions
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
    - location: scripts/create_test_db
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts
      timeout: 300
      runas: root
